Use puppeteer and update dependencies
firstandthird/micro-snaps pull request #2
Opened 2018-04-16 09:57 UTC by AlejandroPerezMartin

2018-04-16 10:34 UTC, Antonio-Laguna commented on routes/main.js
> +          height: parseInt(height, 10) || 800,
This should be `900` as per docs.

2018-04-16 10:34 UTC, Antonio-Laguna commented on routes/main.js
> +      Promise.resolve(outputFile);
What is this?

2018-04-16 10:34 UTC, Antonio-Laguna commented on routes/main.js
> +        return Promise.resolve(null);
No need for this either. Just return `null`

2018-04-17 05:57 UTC, Antonio-Laguna commented on routes/main.js
> +      fs.mkdirSync(dir);
Just seen this, can we use `fs.mkdir` use `util.promisify` to make it `await`able.

2018-04-23 18:10 UTC, ecwillis requested changes

2018-04-23 18:10 UTC, ecwillis commented on routes/main.js
> +        browser = await puppeteer.launch();
Should add and ENV Var as a default so we don't have to pass the `wsEndpoint` to the app every time.

2018-04-24 17:46 UTC, merged